name: mypy

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jpetrucciani/mypy-check@master
        with:
          path: '.'
